### ISSUE TITLE
スマホ版楽器.meで正しくchordを変換できない

### ISSUE THREAD

**Issue by ts-uc** [inajob/toICN#113]
https://instachord.com/community/bug_apps/toicn%e3%81%8c%e6%a5%bd%e5%99%a8-me%e3%82%b9%e3%83%9e%e3%83%9b%e6%9c%80%e9%81%a9%e5%8c%96%e3%82%b5%e3%82%a4%e3%83%88%e3%81%a7%e4%bd%bf%e7%94%a8%e3%81%8c%e3%81%a7%e3%81%8d%e3%81%aa%e3%81%84/

**Comment by inajob** [comment]
重複したものを作ってしまいました。 https://github.com/inajob/toICN/issues/114
本来は後のものを消すべきですが、フォーラムでそっちを報告してしまったので、こちらを閉じさせてください。
