### ISSUE TITLE
Level: 上級者向け について

### ISSUE THREAD

**Issue by U1Nagata** [inajob/toICN#133]
上級者向け　について要望があります

・名称
「上級者向け」→「全て表示」or「省略なし」
に変更したほうが良いと思います

・[!***!] 表示について
ビックリマークを外してほしいです

今後、もっと色んなコードを演奏できるインスタコードが誕生するかも知れません。
ICNはあくまで「度数」と「～」の組み合わせのルールですので
それ以外に独自の表記ルールを作ってはいけないと考えています。
したがって、本レベルも「上級者向け」ではなく、単に「全てのコードを表示している」という位置づけ
そうすると他のレベルは「何かを省略している」という位置づけになるので関係性もわかりやすくなると思います。

**Comment by inajob** [comment]
良さそうに思います。
`[! ... !]`表示は、デバッグの意味もかねて出していただけで深いこだわりはありません。

あえてあるとすれば インスタコードではこのコードは弾けないことを明示したいだけでしたが、今はモードによりそれが実現されているので、その配慮も不要です。

**Comment by U1Nagata** [comment]
こちらの実装はいつになりそうでしょうか？
チュートリアルと作ろうと思い気づいたのですが
Lv.2 を無くして  

Lv.1 初心者向け
Lv.2 標準
Lv.3 省略なし
にしたほうがスッキリするし実用的だと感じました
標準で弾いて違和感を感じた時は、Lv.3を確認する・・・という手順が良いのではないかと。

**Comment by inajob** [comment]
特に問題なさそうなのでマージしました。
新しいブックマークレットを登録している人には自動で新しいバージョンが使えるようになります。
