### ISSUE TITLE
カポ機能とtoICNの変換について

### ISSUE THREAD

**Issue by inajob** [inajob/toICN#139]
https://instachord.com/community/bug_apps/%E3%82%AB%E3%83%9D%E8%A8%AD%E5%AE%9A%E3%81%8C%E3%81%82%E3%82%8B%E6%A5%BD%E8%AD%9C%E3%81%AEtoicn%E3%81%AE%E4%BB%95%E6%A7%98%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6/

カポ機能を設定しているときに今のtoICNの仕様では期待した動作をしないとのこと。

（自分はカポ機能を使っていないので、正しい挙動がちゃんとわかっていない。まずは期待する動作がどんなものかを整理する必要あり。）

**Comment by U1Nagata** [comment]
例えば
https://www.ufret.jp/song.php?data=47385
パプリカの場合

現在はキー判定が A になっていますが

Original Key: G/Em +2

のように表記されると良いです。

**Comment by inajob** [comment]
@U1Nagata あ、そうか ICNは今のままで良くて、カポの表示とそれを加味したキーが表示されれば良いということですね。

**Comment by inajob** [comment]
@U1Nagata 

自分がカポについてあまり理解していないのですが、

Aでカポ0で演奏するのと
G/Em+2 で演奏するのは

インスタコードとしては構成音は同じように思うのですが、その認識は合っていますか？

**Comment by U1Nagata** [comment]
そうですね
現状、Original Key の表記が A になっていますが
Keyのプルダウンから G を選択した時の数字が表示されるので、キー表記と一致していないんですよね。

なのでプログラムを大きくイジる必要はなくて、Original Keyの表記を変えれば大丈夫です。

**Comment by U1Nagata** [comment]
@inajob 
> Aでカポ0で演奏するのと
> G/Em+2 で演奏するのは

演奏されるコードは同じですが
構成音は違います。

G/Em+2 の場合、G/Em の構成音をそのまま2音トランスポーズした音程を発しています。

**Comment by inajob** [comment]
なるほど、確かにちょっと響きが違いますね。
楽譜上でカポが指定されているものは、インスタコードでも、同じようにカポを設定して弾くのが良いんですね。
そのためにはちゃんと表記を出す必要がありますね。

このIssueの必要性がわかってきました。

**Comment by U1Nagata** [comment]
転調の問題というのは
さきほどのパプリカの場合
サビの「パプリカ花が咲いたら」の部分で転調しています。

キーをE/C#m にするときれいなICNが表示されると思います。

しかし、Original Key の表記通りに A で弾いてしまうと、E ではなく F# にしないといけません
しかしtoICNのキー設定を F# にしたら誤ったICNが表示される…ということです

**Comment by inajob** [comment]
ufretのICNを見てサビの「パプリカ花が咲いたら」の部分で転調しているのは察しが付くのですが、そこでキーをE/C#mにするときれいなICNになるというのは、 今回の修正で `Original Key: G/Em +2` と表示すると、わかる人にはわかるようになるという事でしょうか？

（自分にはわからなかったです。）

**Comment by inajob** [comment]
もともとカポを考慮する仕組みはののゆーさんによって導入されており、その動きは今回の要件とは異なるもののようです。

具体的には、推定したキーをカポ分だけずらしたものをオリジナルのキーとする、というロジックになっていました。
今のロジックの場合は、インスタコードでは楽譜の指示は無視してカポ0で演奏すれば原曲キーで演奏できる状態です。
（構成音はカポの物とは変わりますが）

今回 提案された方法に直すと、カポ付きの楽譜は、インスタコードでも同じようにカポを合わせる必要が出てきます。

どちらでもコードは同じなので、それっぽい演奏ができるように思うのですが、今回の提案の方が良いという明確な理由があれば知りたいです。

音楽周りに疎くて、今更な質問かもしれませんが、よろしくお願いします。　@U1Nagata

**Comment by inajob** [comment]
https://github.com/inajob/toICN/blob/481765ca6d17b1e5eda643c9353298502a39693e/toICN.user.js
にて 提案いただいた方法を実装してみました。

が、作ってみて気づきましたが、フォーラムのwatarunrtさんの要望はどうもこれとは違うようですね。

**Comment by inajob** [comment]
## watarunrt さん要望

現状のカポは無視してインスタコードはカポ0で演奏すればよいICNが表示されているが、この状態でtoICNのUIからキーを変更すると**カポを無視していない**コードから変換が行われているように見える。

というバグ報告

## @U1Nagata さん案

楽譜にカポがある場合はインスタコードにも同様にカポを設定する。それを踏まえたICNを表示し、toICNのUIにキーとカポを表示する。

**Comment by inajob** [comment]
（ひとまず昼休み終了なので続きは今度・・）

**Comment by U1Nagata** [comment]
ごめんなさい
実装したjsを実行する方法が分かってないんです。

が、それはさておき
おっしゃるとおり watarunrt さんの要望とは違う解決策で、プログラム的に楽な方法を提示しました。

**Comment by inajob** [comment]
プログラム上の難しさはさほど変わりません。
自分はカポの設定が面倒なので、キーの変更だけでできる今の方法も良いかな、と思っておりwatarunrtさんの提案された修正でも良いかなと思っています。

音楽的に優劣がないのであれば、私の好みで決めてしまおうと思います。

**Comment by U1Nagata** [comment]
@inajob 
いま、watarunrt さんが要望された部分の修正って反映されました？

**Comment by inajob** [comment]
いえ、何もしていないです。

**Comment by U1Nagata** [comment]
あ、勘違いでした

watarunrt さんが指摘している問題点を要約すると

Original key の表記だけカポを反映した正しい音で表記されいるのに
その他のエンジンの部分はカポが反映されていない
ので表記が一致しないという点です
それによって不便なことが３つ生じます

もっと分かりやすい例で
地上の星／中島みゆき で説明します
https://www.ufret.jp/song.php?data=3986

toICNを使うと
Original Keyは F と表示されています

・問題１：表示されるコードが違う

最初のコードは６なので
インスタコード本機は Dm が割り当てられています

toICNの設定で
Mode : OFF（変換前のコードを表示）
にした場合
最初のコードはAmと表記されており、本機の表示と異なります


・問題２：プルダウンでのキー表示が違う

Original Key はFと表示されています
しかしプルダウンから F を選択した時のICNはAutoの時と異なります
プルダウンからCを選択したときの ICN がAutoで表示されています


・問題３：転調を見つけられない

次に転調がわかりにくいという点も問題２と中身は同じです。

コード記号の色を見ると曲の終盤で転調しているのが分かります。

手探りでどのキーに転調しているのか探す場合
プルダウンからキーを一つ一つ変えていくと
Db できれいに表示されることが分かります。
しかし、本機をDbに設定しても正しい演奏は出来ません。

この転調は、曲の最後に半音上がる転調なんです。
C を基準にすると、Dbは半音上だということが分かりますよね？


これらの問題は
watarunrt さんが書かれているとおり
分かっている人なら、カポを0にするか「簡単弾き」をOFFにすればセルフで解決できます

**Comment by U1Nagata** [comment]
@inajob 

ちなみにInstaChordizerでAuto機能をONにした時は、
U-fretのページを読み込むと、簡単弾きを解除するという処理を入れています。

それが一番良いかも。

**Comment by inajob** [comment]
watarunrt さんの提案された修正を行いました。

https://github.com/inajob/toICN/pull/142

これにより https://github.com/inajob/toICN/issues/139#issuecomment-961634392 の 問題2と問題3を解消できます。

カポ設定は楽譜サイトごとに用意されており、変更できないサイトなどもあるので、現状の挙動（カポ設定を認識し、その分だけキーをずらす）のままでバグを直していこうとおもいます。

問題1はOffモードの仕様としては、「変換前のコードを表示する」なので、仕様通りということで、このままにします。

**Comment by inajob** [comment]
@U1Nagata 

一度消してしまった toICN.bookmarklet を復活させました。
PCのブラウザのブックマークレットにこのファイルの内容をコピペすると、動作確認ができます。

例えば  https://github.com/inajob/toICN/pull/142 の場合は下記です。
https://github.com/inajob/toICN/blob/1818045f9765aaa207932e5f7aef3b8307f25c69/toICN.bookmarklet

**Comment by inajob** [comment]
カポを考慮し KeyはF/Dm と判定されますが、転調でF/Dmを選択した時正しく変換できることを確認しました。
![image](https://user-images.githubusercontent.com/291177/140597946-97d63615-1956-4cbb-b765-00edc6b11c85.png)

**Comment by U1Nagata** [comment]
@inajob 
ご対応ありがとうございます
J-total Music で動作が反映されていのを確認しました。

https://music.j-total.net/data/011sa/013_sakamoto_kyu/001.html

**Comment by inajob** [comment]
あー、J-total Musicはもともとカポを認識せずに上部のバーにある
`Original Key：G# / Capo：1 / Play：G`
のOriginal KeyとPlayを見て変換していましたね。

結果としてCapoが0扱いになり変な挙動をしています。

今回のバグとは直接は関係ないですが、ついでに直します。

**Comment by inajob** [comment]
カポをtoICNのUIに表示する案は、作りましたが、採用しません。
https://github.com/inajob/toICN/pull/140

**Comment by inajob** [comment]
J-total Musicのカポの認識が出来ていない問題もこちらで直しました。

https://github.com/inajob/toICN/pull/142

**Comment by U1Nagata** [comment]
確認しました！
問題１については
U-fretは「簡単弾き」をONにしていると不具合が生じるのでOFFにして使いましょう
というアナウンスを入れるようにします。

**Comment by inajob** [comment]
問題1については、OFFモードの仕様上は正しい挙動だと思うので、 「不具合」というのは少し違和感があります。
演奏上あまり役に立たない表示になるのはその通りだと思いますが・・

**Comment by U1Nagata** [comment]
そうですね
「不具合」ではバグになってしまいますもんね。
「不都合」か「問題」と言うようにします。

**Comment by inajob** [comment]
そうですね、（不具合という言葉に敏感なエンジニアです・・）OFFモードがあることが逆に利用者に混乱をきたすようであれば文言を変えたり、モード自体を消すこともできます。

ひとまずここまでの変更は今日の午後あたりにマージする予定です。

**Comment by inajob** [comment]
マージしました。
