### ISSUE TITLE
ICN仕様変更（# > b 表記に）

### ISSUE THREAD

**Issue by U1Nagata** [inajob/toICN#143]
すみません
インスタコード本機とICNの仕様を大きく変更することにしました。

具体的には本機の＃ボタンを♭ボタンに変えます。
それに伴いICNの表記も変更します。

申し訳ありませんが toICN も仕様変更に合わせてプログラムを修正していただけますでしょうか。

1# > 2b
2# > 3b
4# > 5b
5# > 6b
6# > 7b

リリースは、インスタコード周りの全てのアプリが修正を完了した後
1月上旬に本機のアップデートと同時にリリースする予定です。

音楽的にも操作性的にも
＃より♭の方がメリットが多いと気づいて、かなり迷ったのですが
まだユーザーが4000人しかいない今のうちに変えてしまう決断をしました。

とりあえずスケジュール的に可能かどうかお返事いただけますか？

**Comment by inajob** [comment]
12月末を目途に変更に挑戦しますね！
（メリットが大きいというのはどういう点か？などいちユーザーとして気になります！ 　きっとアナウンスページなどで説明があると思うので楽しみにしています！）

**Comment by inajob** [comment]
@U1Nagata 

念のため確認させてください。

キーがCの場合
`C#m`は今まで `1#~` でした が 新しい仕様だと `2b` と`~`が付かないのが期待する動作ですよね？

**Comment by U1Nagata** [comment]
@inajob 
いえいえ。
現状の♯と同様
全部メジャー
〜でマイナー
です。

**Comment by inajob** [comment]
ああ、失礼しました。しばらく空くと忘れますね・・

**Comment by inajob** [comment]
@U1Nagata 以下に修正版を用意しました。自分では合っているつもりなのですが、確認してほしいです。
https://github.com/inajob/toICN/pull/145

**Comment by inajob** [comment]
リリースしました。
