### ISSUE TITLE
アルファベットのルート → 数値への変換ルール（キー変更に対応するために）

### ISSUE THREAD

**Issue by U1Nagata** [inajob/toICN#16]
ちょっと今までよりもややこしくなりますが
アルファベットのルートを数値に変える手順

♭をb に変換（楽器.me U-fret対策）

RootNum 内部処理用のルートナンバー
C: 0
D: 2
E: 4
F: 5
G: 7
A: 9
B: 11
に変換 

#があったら RootNum を +1 （##は+2）
bがあったら RootNum を -1（bbは-2)

KeyNum キーの値は12種類 
0: C/Am
1: Db/Bbm
2: D/Bm
3: Eb/Cm
4: E/C#m
5: F/Dm
6: F#/D#m
7: G/Em
8: Ab/Fm
9: A/F#m
10: Bb/Gm
11: B/G#m

表示するルートの値は
(RootNum + 12 - KeyNum) % 12 の値を元に決定

0: 1
1: 1#
2: 2
3: 2#
4: 3
5: 4
6: 4#
7: 5
8: 5#
9: 6
10: 6#
11: 7

となります

**Comment by inajob** [comment]
キー変更するときは確かに数字にしたほうがよさそうですね。
（今も数字にはしていますが、白鍵の順が数字になっており、例示されたような半音の数ではないです）

**Comment by inajob** [comment]
この方法とよく似ていますが、今までの実装を生かす形でうまい事キー変更に対応できたので、ひとまずこのIssueは閉じます。
またリファクタリングなどする際に参考にさせていただくかもしれません。

@U1Nagata さん。 アドバイスありがとうございました！
