### ISSUE TITLE
ChordWikiのキーが途中で変わる曲に対応したい。

### ISSUE THREAD

**Issue by inajob** [inajob/toICN#22]
対応したところで、InstaChordでさっと移調できるのか？という問題もあるが・・

- 途中で変わる曲の例
  - https://ja.chordwiki.org/wiki/%E3%81%9B%E3%83%BC%E3%81%AE%E3%81%A3%21

**Comment by U1Nagata** [comment]
いちおうインスタコード本機は転調もできるというスタンスにしています

https://youtu.be/dAfXbfMtLAo?t=439

コード譜ライターではこのように
キーの差分を表示して、# または b を何回押せばいいかを明示しています。

**Comment by inajob** [comment]
https://github.com/inajob/toICN/pull/64
早くも対応！すごい！
