### ISSUE TITLE
N.C. の後のコードが変換されない現象を解消する

### ISSUE THREAD

**Issue by ts-uc** [inajob/toICN#24]
N.C. の後のコードが変換されない現象を解消する

**Comment by inajob** [comment]
ひとまず下記では変換できています。この現象が確認できる曲を教えて欲しいです。

https://ja.chordwiki.org/wiki.cgi?c=view&t=Lemon&key=0&symbol=
![image](https://user-images.githubusercontent.com/291177/132070561-70755625-4b98-4a8c-971c-dbed4a1b994c.png)

**Comment by surrogatepair** [comment]
この現象と関係あるかはわかりませんが、 `Cb` や `E#` がある箇所でコード変換が止まってしまう現象を確認しています。

https://ja.chordwiki.org/wiki/%E3%81%9B%E3%83%BC%E3%81%AE%E3%81%A3%21

移調機能から「♯表記」や「♭表記」を選ぶことで回避可能です

**Comment by inajob** [comment]
https://github.com/inajob/toICN/commit/f374f337afc5fc2fdd191d3fcdd31e1231ce6237
で修正しました。 Cb (= B), Fb (= E) の変換が未サポートだったのが原因のようです。

N.C.の件もこれかな？ 確認が取れればこのIssueは閉じます。 @ts-uc さん、確認お願いします。

**Comment by ts-uc** [comment]
![image](https://user-images.githubusercontent.com/10070734/132076274-97ecfbfb-5b96-415a-92cd-085fdc580254.png)
74e489f37a0b44dde102e0597002863819f2429a の時点ではこのように N.C. の後のコードが変換されない現象があったのですが、現在は改善しているのでこのイシューはクローズしちゃって問題ないです。

**Comment by inajob** [comment]
OKです。閉じます。
