### ISSUE TITLE
シャープ系・フラット系のキーが反映されていない

### ISSUE THREAD

**Issue by surrogatepair** [inajob/toICN#25]
「Key: F#」や「Key: Bb」などの曲のキーがそれぞれ「Key: F」「Key: B」で判定されているようです

**Comment by inajob** [comment]
わすれてた・・ 報告ありがとうございます。

**Comment by inajob** [comment]
https://github.com/inajob/toICN/commit/8fbd10324cb16c0ee070e496918ad70adaf88050
で直しました。

Key: Amとかもあったけどこれは対応方法がよくわからないです。 マイナーコードの場合はmの付くパターンが変わる？

**Comment by inajob** [comment]
積み残しはこちら。
https://github.com/inajob/toICN/issues/26
