### ISSUE TITLE
オンコードの扱い

### ISSUE THREAD

**Issue by U1Nagata** [inajob/toICN#29]
C/E または ConE というコードの場合
今後の開発計画を考慮すると
1/3
というふうに両方表記してもらったほうが良いのですが
このとき、ベース音（右側の符号）にメジャー、マイナーの考え方はないので、[~]Swap の処理は行わず数字だけを表示することになります。

**Comment by inajob** [comment]
- https://github.com/inajob/toICN/pull/54
