### ISSUE TITLE
他のコード譜サイトにも対応させたい

### ISSUE THREAD

**Issue by inajob** [inajob/toICN#32]
候補募集中です。

**Comment by surrogatepair** [comment]
邦楽であれば、大手3サイト（いずれも企業運営）
* U-フレット
* 楽器.me https://gakufu.gakki.me/
* J-Total Music https://music.j-total.net/

に対応しておけばだいたいなんとかなるかと思います。

その他、個人サイトレベルでまとまった変換ができそうなのはアニソンコード譜集（ http://anison.y-lab.org/ ）辺りですかね……

洋楽であれば、ChordWiki同様の投稿型サイトで Ultimate Guitar Tabs（ https://www.ultimate-guitar.com/ ）というサイトがあります

**Comment by inajob** [comment]
対応を増やすと確認作業が煩雑になりますね・・自動化できないかな・・

**Comment by inajob** [comment]
楽器.me は簡単に対応できた。 https://github.com/inajob/toICN/pull/43

J-Total MusicはちょっとHTMLの構造が期待したものと違うので、面倒そう・・

**Comment by inajob** [comment]
- https://github.com/inajob/toICN/issues/44

J-Total Musicに対応させました。

挙げられたサイトはとりあえず対応できたのでこのIssueも閉じます。また対応したい（してほしい）サービスが出てきたらIssueを作りましょう。
