### ISSUE TITLE
キーの手動切り替え機能が欲しい

### ISSUE THREAD

**Issue by ts-uc** [inajob/toICN#33]
* 自動認識したキーを表示し、
* 必要に応じてキーを手動で切り替えできる

機能が欲しいです

**Comment by inajob** [comment]
地味に面倒そうな機能ですが・・欲しいですね！

**Comment by inajob** [comment]
https://github.com/inajob/toICN/issues/34 まずは表示だけをやります。

**Comment by inajob** [comment]
雑すぎる表示を実装したが、このIssueを達成するためにはもう少しリッチなUIが欲しい所

**Comment by inajob** [comment]
Issueの内容が達成できたので閉じます。
