### ISSUE TITLE
Cのキーしか対応していない

### ISSUE THREAD

**Issue by inajob** [inajob/toICN#4]
ChordWikiもU-FRETも移調機能があるので、組み合わせれば一応演奏はできるが、別のキーも認識できると嬉しい。

キーの認識アルゴリズムはゆーいちさんから聞いている

ChordWikiの曲は場合によってはキーが書かれているのでそれがあるときはそっちを使うのが良い。

**Comment by ts-uc** [comment]
曲によって、途中からキーが転調することがあり、それに対応したコードを書く必要がある

**Comment by inajob** [comment]
ChordWikiにてKeyが明示してある場合は、そのキーで処理できるようにしました。

https://github.com/inajob/toICN/pull/20

出来ないこと

- 曲の途中でキーが変わる
  - 最後まで初めのキーで処理します。
- キーが明記されていない
  - C決め打ちで処理します。
- U-FRETはキーが明記されていない
  - C決め打ちで処理します。

**Comment by inajob** [comment]
未処理の事項について、後続のIssueを作成したので、このIssueは閉じます。
