### ISSUE TITLE
UIの改善

### ISSUE THREAD

**Issue by ts-uc** [inajob/toICN#51]
ダイアログでキーを表示した上で入力させるっていうのはスマートではないので改良したい

**Comment by ts-uc** [comment]
iframeで操作ボタンを作ろうとしたが、XSS対策で表示されないサイトが多く、他の方法を検討する必要がありそうです。

**Comment by inajob** [comment]
むりやりフローティングウィンドウみたいなのをページに追加するしかなさそうですね・・
ちょっと下品な気がしてあまりやりたくないですが・・

**Comment by inajob** [comment]
https://github.com/inajob/toICN/pull/101 で実装されました。 すごい！かっこいい！
