### ISSUE TITLE
楽器.me 「コード名表示」モードでの判定

### ISSUE THREAD

**Issue by U1Nagata** [inajob/toICN#65]
楽器.meは
画面上部の「ギター（コード名表示）」をクリックするとギターの指使いの画像が消えて見やすいのですが、このときHTMLのソースがまるごと変わるので対応が必要です。

コード記号が
<u class="blue"></u> で囲われます

**Comment by surrogatepair** [comment]
「ギター（全コード表示）」の場合でも、フレットボード表示非対応のコードのHTMLタグが変わってしまうようで、対応が必要かと思います

https://gakufu.gakki.me/m/data/N13947.html

**Comment by U1Nagata** [comment]
ホントですね！ありがとうございます。
しかもタグで囲われてない…

しかし楽器meのコード解釈はひねくれてますよね…（個人の見解です）
フレットボードが表示されないのは、そういうクセの強いコードですし、インスタコードでは再現できないので、あえて表示されなくても良いかも。

そこまで楽器meに寄り添わず、こういう時は他のサイトを見て下さいというスタンスでも良いかな
（個人の見解です２）

ただ「ギター（コード名表示）」の方は見やすいので対応してほしい。

**Comment by surrogatepair** [comment]
＃ ChordWikiで更にひねくれた表記を量産しまくってる人です、ついついテンション盛りまくりたい習性なので申し訳ない……

楽器.meの場合は「インスタコードで対応可能な単純なコードのonコード」でもフレットボードが表示されなくなるので、今後の開発計画（#29）を加味すると表示がほしいとは思います  
（運用でカバーするなら「ギター（コード名表示）のほうを見て下さい」でも十分ですね）

**Comment by inajob** [comment]
「ギター（コード名表示）」 https://github.com/inajob/toICN/pull/79 にて対応しました。 

フレットボードが表示されない曲は別のIssueで対応しますね　→ https://github.com/inajob/toICN/issues/80
