### ISSUE TITLE
M7, maj7,△7のような別名表記がサイトに存在するか？

### ISSUE THREAD

**Issue by inajob** [inajob/toICN#7]
今はM7のみ対応している。
maj7, △7などが存在するなら対応が必要。

**Comment by ts-uc** [comment]
https://ja.chordwiki.org/cd.html
ChordWikiのコード一覧が参考になると思います

**Comment by U1Nagata** [comment]
maj7は頻出なのでM7に変換したほうが良いと思います。
あと [7-5] ≠ [m7-5] なので

変換せずにそのまま活かして
5[7-5] のように表記していただきたいです。
その他[13] [11] なども同様。

今後のアップデートで弾けるようにするのは不可能ではないので。

**Comment by inajob** [comment]
@U1Nagata ひとまず弾けるコードを優先します。未対応の場合は [!!7-5!!]みたいに !!で囲んで出るようになっています。

maj7の変換は https://github.com/inajob/toICN/pull/15 で対応できました。

**Comment by inajob** [comment]
M7やmaj7に対応できたので閉じます。
またほかの修飾子でも同じような問題があれば都度Issueを作りましょう。
