### ISSUE TITLE
iPhoneでの動作報告が欲しい

### ISSUE THREAD

**Issue by ts-uc** [inajob/toICN#73]
iPhoneでの動作報告が欲しいです。

**Comment by inajob** [comment]
![image](https://user-images.githubusercontent.com/291177/132265867-76d48b00-e1c3-4aa4-9a31-46472b7ed0b4.jpeg)

iPhoneのSafariで動いてます。Android Chromeのようなテクニックは不要で、普通にブックマークメニューから選べばOKでした。

**Comment by inajob** [comment]
(画像がでかい・・

閉じます。

**Comment by ts-uc** [comment]
了解です。このイシューを閉じます
