### ISSUE TITLE
普通のコードの背景を白にしたい

### ISSUE THREAD

**Issue by U1Nagata** [inajob/toICN#77]
U-FRET の動画プラスで再生した場合、現在の演奏中のコードの背景が黒くなるので、文字が隠れてしまいます。
背景色なしのコードの背景を#FFF にしても問題ないですかね？

https://www.ufret.jp/song.php?data=72732

僕がソースいじると壊しそうなので、ご対応いただけると嬉しいです

**Comment by ts-uc** [comment]
湯〜イチさんへ
↓のページを開いて、ここに書かれているブックマークレットを適用してみてください。直ってるはずです
https://github.com/ts-uc/toICN/tree/chordbackwhite

**Comment by inajob** [comment]
動作確認できたのでマージしました。 

動画プラス面白いですね！　ちゃんと動画下のコードもICNになるのは知らなかったですｗ

**Comment by U1Nagata** [comment]
確認しました！
一応、スマホのダークモードで見ても、どのサイトも背景は白になるようなのでこれで良いと思います。
近々、みやびさんのYouTubeでレビュー動画を出してくれるので、それが公開されたらインスタコードの公式HPの「使い方」でも紹介しようと思います。
