### ISSUE TITLE
古い J-Total Music! のページでchordが正しく変換されない

### ISSUE THREAD

**Issue by ts-uc** [inajob/toICN#81]
少し昔に採譜された曲だと全然書式が違って、その曲の場合は変換されません。
例: https://music.j-total.net/data/005o/067_ono_erena/004.html

**Comment by inajob** [comment]
ぱっと見　Keyの要素が取得できていないだけのようですね。 コード一覧は取得できている

**Comment by inajob** [comment]
手元でKeyの取得をコメントアウトしたラ上手く動いた（自動推定でキーもうまく設定された）

**Comment by inajob** [comment]
- https://github.com/inajob/toICN/pull/105

少し強引に対応しました。まだほかの形のHTMLがあるかもだなぁ・・
