### ISSUE TITLE
マイナースケールモードへの対応

### ISSUE THREAD

**Issue by ts-uc** [inajob/toICN#82]
現状情報が不足しているのですが、インスタコードにはマイナースケールモードが実装されるらしく、それに対応させたいです。
現状分かっている情報はこれだけ → https://twitter.com/insta_chord/status/1431449068589379584

以下、上のツイートより引用

メジャー
1:C 2:Dm 3:Em 4:F 5:G

マイナー
1:Am 2:Bm 3:C 4:Dm 5:E

になります
5がEmじゃなくてEになってるところがミソです

**Comment by inajob** [comment]
やるにしてもまだmainにはマージせずにやる感じですかね？（使う人が混乱しそう

**Comment by ts-uc** [comment]
実装はするが現状使わない（常にメジャースケールモードで表示）、でいいと思います

**Comment by ts-uc** [comment]
もっとも、現状で情報が大きく不足してるので実装するのは先のことになりそうですが・・・

**Comment by inajob** [comment]
すでに実装されている？
https://instachord.com/community/music/%e7%9f%ad%e8%aa%bf%e3%81%ae%e5%a0%b4%e5%90%88%e3%81%ae%e3%82%b3%e3%83%bc%e3%83%89%e6%95%b0%e5%ad%97/

**Comment by U1Nagata** [comment]
クラシックやポップスの教科書では、Cメジャーキー（長調）かAmキー（短調）かを明確に区別するので、AmをVImじゃなくてImで表記します。
ジャズの世界で使われるナッシュビルナンバーでは、長調・短調の区別はなく、Amを6で表記します。

インスタコードでは、基本的に後者の「長調・短調を区別しないアプローチ」で演奏する楽器として開発しました。
ポップスでは長調・短調の区別がない場合も多いですし、区別しない方が覚えることが少なくて良いので、コード進行を感覚的に捉える近道だと考えたからです。

しかし、クラシックやポップスをちゃんと学んだ人は、すでに長調・短調を区別して捉える方法が身に染み付いているので、Amを6として捉えられない場合があります。
そういう人のための救済策としてインスタコードにはマイナー・スケールモードを用意しています。
上記のフォーラムに書き込んだユーザーさんは、そっち系の人（ちゃんと学んだ人）です。

そういう人は、コード記号を見ただけ、あるいは曲を聞いただけ感覚的に数字に変換できるので、toICNのようなアプリも必要ない場合が多いです。

ただ、今後、要望が出てくるのは確かです。

追加機能の理想としては
ChordWiki限定で
「メジャーキー、マイナーキーを区別して数値化する」
という項目のON-OFFを選択できると喜ぶ人はいると思います。

**Comment by ts-uc** [comment]
なるほど！

**Comment by ts-uc** [comment]
現状、インスタコード本体に # と ~ が同時に使えないバグがあるので、それが修正され次第インスタコードの仕様を調べてこの機能に対応させたいと思います

**Comment by ts-uc** [comment]
マイナースケールモードが実装されたので閉じます
