### ISSUE TITLE
原因不明 表示できない曲

### ISSUE THREAD

**Issue by U1Nagata** [inajob/toICN#83]
https://ja.chordwiki.org/wiki/%E7%82%8E

C# が 7 になるはずなんですが
変換できていないです

他の曲で調べても再現できない

**Comment by inajob** [comment]
7になっているように見えます、最新版で試してもらえますか？

**Comment by U1Nagata** [comment]
最新版じゃなかったみたいです
修正されてました！

**Comment by U1Nagata** [comment]
https://ja.chordwiki.org/wiki/%E5%8D%88%E5%89%8D8%E6%99%82%E3%81%AE%E8%84%B1%E8%B5%B0%E8%A8%88%E7%94%BB

これが原曲キー「B」のときにうまく変換できないのは何故でしょう？

**Comment by inajob** [comment]
![image](https://user-images.githubusercontent.com/291177/132508034-2f7b7056-7532-44ae-8eab-e74498c17c91.png)
コードのタグがこうなってて コードの前に `| `がついてるのが原因でうまくコードを認識できていないですね。

**Comment by inajob** [comment]
ChordWikiもうまく認識できていないので、これはサポートしないで良いかな？と思います。

**Comment by surrogatepair** [comment]
ChordWiki側でも移調機能が機能しなくなると問題視されてるやつですね……  
https://ja.chordwiki.org/wiki.cgi?c=note&t=Pretender

とりあえず非対応で問題ないかと思います

**Comment by U1Nagata** [comment]
なるほど
ルール違反なんですね！
確かに縦線書きたい気持ちは分かりますが
お調べいただきありがとうございます

**Comment by inajob** [comment]
大丈夫そうなので閉じます。
